# =============================================================================
# Device Profile: NVIDIA Jetson Nano
# Wi-Fi: wlan0 | HW codec: nvv4l2h264enc/nvv4l2h265enc + nvv4l2decoder
# =============================================================================

[device]
name  = jetson
iface = wlan0

[source]
camera_device = /dev/video0
element       = v4l2src
caps_format   = YUY2
need_convert  = true

[encoder]
h265_element      = nvv4l2h265enc
h265_extra        = preset-level=1 insert-sps-pps=true idrinterval=30 iframeinterval=30 maxperf-enable=true
h264_element      = nvv4l2h264enc
h264_extra        = preset-level=1 insert-sps-pps=true idrinterval=30 iframeinterval=30 maxperf-enable=true
bitrate_unit_kbps = false

[decoder]
h265_element = nvv4l2decoder
h265_extra   =
h264_element = nvv4l2decoder
h264_extra   =

[sink]
hdmi    = nv3dsink
display = autovideosink

[network]
rtp_pt_h265    = 96
rtp_pt_h264    = 97
stream_port    = 5600
rtsp_port      = 8554
peer_ip_host   = 192.168.77.1
peer_ip_client = 192.168.77.2