# =============================================================================
# Device Profile: Raspberry Pi 4B
# Wi-Fi: wlan0 | HW encoder: v4l2h264enc (H.264 only HW, H.265 SW)
# =============================================================================

[device]
name  = rpi4
iface = wlan0

[source]
camera_device = /dev/video0
element       = v4l2src
caps_format   = YUY2
need_convert  = true

[encoder]
h265_element      = x265enc
h265_extra        = speed-preset=ultrafast tune=zerolatency
h264_element      = v4l2h264enc
h264_extra        = extra-controls="controls,video_gop_size=30"
bitrate_unit_kbps = true

[decoder]
h265_element = avdec_h265
h265_extra   =
h264_element = v4l2h264dec
h264_extra   =

[sink]
hdmi    = kmssink
display = autovideosink

[network]
rtp_pt_h265    = 96
rtp_pt_h264    = 97
stream_port    = 5600
rtsp_port      = 8554
peer_ip_host   = 192.168.77.1
peer_ip_client = 192.168.77.2
